version: "3"
services:
    4fd7f22c-pgweb:
        command:
            - pgweb
            - --bind=0.0.0.0
            - --listen=8081
            - --binary-codec=hex
        container_name: 4fd7f22c-pgweb
        depends_on:
            - 4fd7f22c-postgres
        environment:
            DATABASE_URL: postgres://dev-node:insecure-change-me-in-prod@postgres:5432/substreams?sslmode=disable
        image: sosedoff/pgweb:0.11.12
        links:
            - 4fd7f22c-postgres:postgres
        ports:
            - target: 8081
              published: 8081
        restart: on-failure
    4fd7f22c-postgraphile:
        command:
            - --connection
            - postgres://dev-node:insecure-change-me-in-prod@postgres:5432/substreams?sslmode=disable
            - --watch
            - --cors
        container_name: 4fd7f22c-postgraphile
        depends_on:
            - 4fd7f22c-postgres
        image: graphile/postgraphile:4
        links:
            - 4fd7f22c-postgres:postgres
        ports:
            - target: 5000
              published: 3000
        restart: on-failure
    4fd7f22c-postgres:
        command:
            - postgres
            - -cshared_preload_libraries=pg_stat_statements
        container_name: 4fd7f22c-postgres
        environment:
            POSTGRES_DB: substreams
            POSTGRES_HOST_AUTH_METHOD: md5
            POSTGRES_INITDB_ARGS: -E UTF8 --locale=C
            POSTGRES_PASSWORD: insecure-change-me-in-prod
            POSTGRES_USER: dev-node
        healthcheck:
            test:
                - CMD
                - pg_isready
                - -U
                - dev-node
            timeout: 4s
            interval: 5s
            retries: 10
        image: postgres:14
        ports:
            - target: 5432
              published: 5432
        restart: on-failure
        volumes:
            - type: bind
              source: ./data/postgres
              target: /var/lib/postgresql/data
    4fd7f22c-sink:
        container_name: 4fd7f22c-sink
        depends_on:
            - 4fd7f22c-postgres
        entrypoint:
            - /opt/subservices/config/start.sh
        environment:
            DSN: postgres://dev-node:insecure-change-me-in-prod@postgres:5432/substreams?sslmode=disable
            OUTPUT_MODULE: db_out
            SUBSTREAMS_API_TOKEN: eyJhbGciOiJLTVNFUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjIwMTgxMTkwNTksImp0aSI6IjE5MDcxYWViLWFhNWQtNGM0OS1iZGI4LWE3OWY0NjI1ZjE0ZiIsImlhdCI6MTcwMjc1OTA1OSwiaXNzIjoiZGZ1c2UuaW8iLCJzdWIiOiIwdmFrYTY4NDhlYTBjMTJkYTVhMDIiLCJ2IjoxLCJha2kiOiIyYWMwMTQyYWJmZDViZDViOTZiYWE0ODZhYTkwZDUxN2Y5MmM1MmI1OGRiNDI1NjBlY2VjNGJhOGQyYjYyNDA2IiwidWlkIjoiMHZha2E2ODQ4ZWEwYzEyZGE1YTAyIn0.2gfLr6kQxJXeYwvOxa5kw54URlfViAxltvTlH4aYPE4hMWaCJcTRQb3GGUdLSBKd2hzgvQVhidHFPdUrs-2Wcg
        image: ghcr.io/streamingfast/substreams-sink-sql:v4.0.0-rc.2
        links:
            - 4fd7f22c-postgres:postgres
        restart: on-failure
        volumes:
            - type: bind
              source: ./data/sink
              target: /opt/subservices/data
            - type: bind
              source: ./config/sink
              target: /opt/subservices/config
    4fd7f22c-sinkinfo:
        command:
            - postgres://dev-node:insecure-change-me-in-prod@postgres:5432/substreams?sslmode=disable
        container_name: 4fd7f22c-sinkinfo
        depends_on:
            - 4fd7f22c-postgres
        image: dfuse/sqlsinkinfo:latest
        links:
            - 4fd7f22c-postgres:postgres
        ports:
            - target: 8282
              published: 8282
        restart: on-failure
